#!/bin/bash


function docker_stops(){
    docker ps --format="{{.ID}}" | xargs docker stop
}


function java_envs(){
    /usr/libexec/java_home -V   
}


function b64(){
    arg=""
    while [ "$1" != "" ];do
        case $1 in
            -d | --decode | -D )
                arg="-d"
                shift
                break
                ;;
            * )
                break
                ;;
        esac
    done
    if [[ "$arg" == "-d" ]]; then
        echo "$1" | base64 -D
    else
        echo "$1" | base64
    fi

}
